### ISSUE TITLE
About train PlaneNet from scratch

### ISSUE THREAD

**Issue by FangGet** [art-programmer/PlaneNet#1]
Thanks for opensourcing PlaneNet, Its behavior at corridor is amazing.

I'd like to train a revised PlaneNet from scratch, while the data your team provided has no planenet_scannet_train.tfrecords.
Would it be possible for you to share this this part of data? or just the scannet to tfrecord bash?

**Comment by art-programmer** [comment]
Thank you for your interests in our work. I just added the training data. Please see the README for details.

**Comment by FangGet** [comment]
Thanks so much!!

**Comment by FangGet** [comment]
thanks to your train data, after some struggle with tensorflow, I finally train the revised net successfully.
