### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by husonchen** [art-programmer/PlaneNet#12]
https://mega.nz/#!sjpT2DiQ!Uo-6hxyldmtnPoKk3TTdUHKZADRGy6nIPlmAeVzJs_8
It returns:
Sorry, something went wrong.

**Comment by husonchen** [comment]
And also the link of tfrecords for testing is also broken.
@chenliu-wustl

**Comment by DRAhmadFaraz** [comment]
@husonchen I have this file. If you want then I can help you.

**Comment by husonchen** [comment]
@DRAhmadFaraz Thanks a lot! Could you share this file with me? Is it possible that sharing testing tfrecords at the same time?  I would appreciate that. My email xchenci@connect.ust.hk

**Comment by art-programmer** [comment]
@husonchen I don't know why but I can open the links and download on my side. Maybe an Internet connection issue?

**Comment by art-programmer** [comment]
FYI, I just copied those files to Google Drive and updated links in README.
