### ISSUE TITLE
Strange normal values

### ISSUE THREAD

**Issue by pwmorrison** [art-programmer/PlaneNet#15]
Hi, thanks for the great paper and code.

I have the code working ok, but the normals it predicts look very strange to me. For example, for a vertical surface I'd expect the y-component to be near zero, but it has a large value. I expected the normals to be in the cameras 3d coordinate system, but they dont seem to be?

Could you please provide more information on this, or why i might be seeing strange values?

Thanks!

**Comment by art-programmer** [comment]
Sorry that I forgot to explain the coordinate system. We use a coordinate system where y points to the front, so it makes sense for a vertical plane to have large y values. I've updated the README file accordingly,

https://github.com/art-programmer/PlaneNet/blob/master/README.md#plane-representation

Thanks for the great suggestion.

**Comment by pwmorrison** [comment]
Thanks, that makes more sense.
