### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by CC9310** [art-programmer/PlaneNet#19]
when I run preidct.py, The error happens as following:
`File "/home/xc/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./nndistance/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE
`
What should I do?

**Comment by ghost** [comment]
@DiscoDiscoBoomBoom did you find a solution for this?

**Comment by dwindy** [comment]
> when I run preidct.py, The error happens as following:
> `File "/home/xc/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.NotFoundError: ./nndistance/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE `
> What should I do?

Hello, did you find the solution for this?
Thanks
