### ISSUE TITLE
The data for training and testing couldn't be downloaded

### ISSUE THREAD

**Issue by reborm** [art-programmer/PlaneNet#2]

**Comment by heng94** [comment]
Hello, I have the same trouble ,Could you please tell me how you solved the problem ? Thanks a lot

**Comment by SeaOfOcean** [comment]
Hello, I have the same trouble +1 @reborm can you share how you solved the problem?

**Comment by art-programmer** [comment]
I don't know why but the links work fine on my side. Anyway, I copied them to Google Drive and put the new links on README. Thanks for your interests in our work!

**Comment by SeaOfOcean** [comment]
@art-programmer Thanks for updating the model download link. I can download the model actually, but I cannot download the training data. Can you upload the training data to google drive as well? Thanks in advance!

**Comment by SeaOfOcean** [comment]
https://wustl.app.box.com/s/d3vmtei5sin40svky6dcbe2aqhh5tmoz download always fail in the middle @art-programmer I have tried the whole day without success. Google drive or dropbox is OK for me.

**Comment by art-programmer** [comment]
I just moved everything to Google Drive and updated the links.

**Comment by SeaOfOcean** [comment]
Thanks for your effort!!!

**Comment by XGuider** [comment]
Google Cloud download is too slow and there will be a breakpoint download in the middle of the road. I have tried many times. Could Baidu Cloud Link? @HanochZzhou @SeaOfOcean @jimeiyang
