### ISSUE TITLE
A problem about PlaneRCNN?

### ISSUE THREAD

**Issue by rxqy** [art-programmer/PlaneNet#21]
Hi, I'm reading your latest paper PlaneRCNN and enjoy your work. Good Job!
However, I have some minor problems regarding the visualization result in your paper. How do you make sure that there's only one bbox/one segmentation detected per plane instance, and how do you make sure that the segmentations never overlap with each other?

Taking Figure 1 (2) as an example, from my understanding, after NMS in MASK RCNN, there can still be multipe bboxes on the same object.
e.g
![](https://raw.githubusercontent.com/endernewton/tf-faster-rcnn/master/data/imgs/pred.png)
In this detection result of faster rcnn, there exists multiple bench or chair bboxes all representing the same object. However, this problem doesn't seem to exist in your result. That's what confuses me.

Did you use any tricks, like adjusting NMS thresholds or set a high confidence score to achieve that? Or did I miss something in your paper?

Many thanks!

**Comment by art-programmer** [comment]
Thank you for your interests in our work. We didn't change the NMS threshold of Mask R-CNN. If two masks have large enough overlap, one of them will be removed. Mask R-CNN allows two instances with different semantics to overlay, but in our case, all instances have the same semantic ("plane"). So two instances never have a large overlap.

**Comment by rxqy** [comment]
Get it. Many thanks!
