### ISSUE TITLE
Pre-trained model for PlannRCNN

### ISSUE THREAD

**Issue by siyuada** [art-programmer/PlaneNet#22]
Hey, thanks for your excellent work. 
I have tried your PlaneNet version, and wanna used that in kitti dataset, but it worked not really well.
In the paper, I see the huge potential of PlaneRCNN. And there only exists pre-trained model of PlaneNet. Could you please provide your pytorch pre-trained model of PlaneRCNN? 

Really thanks.

**Comment by art-programmer** [comment]
Sorry for the late response. I believe this repo has what you need.
https://github.com/NVlabs/planercnn
