### ISSUE TITLE
how can i get the normal of planes for each frame extracted from /scene_id/scene_id.sens?

### ISSUE THREAD

**Issue by Hui-Yao** [art-programmer/PlaneNet#36]
hello! thanks for your impressive work of this project.

after running parse.py, i got three files:
annotation/segmentation/ *.png : the planr segmentation of each frame
annotation/planes.npy : the global normal for all the planes in the scene
annotation/planes.ply : the 3D mesh model of the scene, and i can open it with meshlab

I think these files should be the correct output of parse.py .

for now, i want to get the normal of planes of each frame extracted from /scene_id/scene_id.sens using the official reader,
but i have saw the document of both PlaneNet and PlaneRcnn, i can`t figure out it.

could you tell me how to solve it ?
thank a lot.
By the way : welcome to contact me at im_huiyao@163.com , if anyone wanna dicuss problems of PlaneNet and PlaneRcnn.
![0](https://user-images.githubusercontent.com/52377012/96607023-807a8780-132a-11eb-92fc-89e0ed7d7b9e.png)

**Comment by nku-zhichengzhang** [comment]
> hello! thanks for your impressive work of this project.
> 
> after running parse.py, i got three files:
> annotation/segmentation/ *.png : the planr segmentation of each frame
> annotation/planes.npy : the global normal for all the planes in the scene
> annotation/planes.ply : the 3D mesh model of the scene, and i can open it with meshlab
> 
> I think these files should be the correct output of parse.py .
> 
> for now, i want to get the normal of planes of each frame extracted from /scene_id/scene_id.sens using the official reader,
> but i have saw the document of both PlaneNet and PlaneRcnn, i can`t figure out it.
> 
> could you tell me how to solve it ?
> thank a lot.
> By the way : welcome to contact me at [im_huiyao@163.com](mailto:im_huiyao@163.com) , if anyone wanna dicuss problems of PlaneNet and PlaneRcnn.
> ![0](https://user-images.githubusercontent.com/52377012/96607023-807a8780-132a-11eb-92fc-89e0ed7d7b9e.png)

Hav u solved problem? Depressing meet same confusion as urs.
Appreciate a lot for sharing!

**Comment by nku-zhichengzhang** [comment]
for network output it can be inferred from P_i. But where in data preparation phase?
