### ISSUE TITLE
Ask for help 

### ISSUE THREAD

**Issue by heng94** [art-programmer/PlaneNet#5]
Hello ,I am a master student in China. I am interested  in your paper,But I have some trouble in README.md at Compilation. I have tried to run the follow "sh compile.sh .But I got the result as follow:

/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status

I went  to  https://www.tensorflow.org/extend/adding_an_op#build_the_op_library    for help .But it gave me the result like it:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_compile_flags'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_link_flags'
compile.sh: 19: compile.sh: Bad substitution

I really don't know how to deal with it  .I would be very grateful if you could give me some advice .
Thanks !

**Comment by art-programmer** [comment]
It might be an issue related with TensorFlow version. Could you please try to run the following Python commands (which you can also find in compile.sh):

import tensorflow as tf; 
print(tf.sysconfig.get_lib());

Then paste the printed directory path and check the content under the directory. There should be a file named libtensorflow_framework.so. Here are some issue pages I found relevant.

https://stackoverflow.com/questions/47906589/tensorflow-op-how-to-include-libtensorflow-framework-so
https://github.com/tensorflow/tensorflow/issues/1248

**Comment by heng94** [comment]
Thanks very much ! I have solved it successfully !

**Comment by kharyal** [comment]
I was trying this with TF 1.14, but I got the same error. I tried downgrading TensorFlow to 1.13.1 and it worked!
