### ISSUE TITLE
nndistance compile error

### ISSUE THREAD

**Issue by zebrajack** [art-programmer/PlaneNet#6]
![image](https://user-images.githubusercontent.com/1118889/42816514-a836646e-89fd-11e8-9bd7-da5e8ae34f18.png)

It seems we don't include the eigen3 in our directory.  could I know what is the specific version of eigen3?

**Comment by art-programmer** [comment]
I am using Eigen 3.2.92.

**Comment by qiwr007** [comment]
I met the same problem. After I installed eigen by the commend "sudo apt-get install libeigen3-dev", it turns out my eigen's version is 3.3, and the problem still exist.
Could you provide some clues to solve this compile error?

**Comment by art-programmer** [comment]
Eigen3.2.9 can be installed by following instructions [here](http://eigen.tuxfamily.org/index.php?title=News:Eigen_3.2.9_released!). You may also want to check the original GitHub [repo](https://github.com/fanhqme/PointSetGeneration) for more information about the compilation.

**Comment by qiwr007** [comment]
After I put the 'eigen3' folder into a new folder 'third_party', things look good now. LOL
